package cldr

// Generated from CLDR version 35
var EN = map[string]Localization{
	"ADP": {"Andorran Peseta", "Andorran peseta", "Andorran pesetas", "ADP", "", ""},
	"AED": {"United Arab Emirates Dirham", "UAE dirham", "UAE dirhams", "AED", "", ""},
	"AFA": {"Afghan Afghani (1927–2002)", "Afghan afghani (1927–2002)", "Afghan afghanis (1927–2002)", "AFA", "", ""},
	"AFN": {"Afghan Afghani", "Afghan Afghani", "Afghan Afghanis", "AFN", "", ""},
	"ALK": {"Albanian Lek (1946–1965)", "Albanian lek (1946–1965)", "Albanian lekë (1946–1965)", "ALK", "", ""},
	"ALL": {"Albanian Lek", "Albanian lek", "Albanian lekë", "ALL", "", ""},
	"AMD": {"Armenian Dram", "Armenian dram", "Armenian drams", "AMD", "", ""},
	"ANG": {"Netherlands Antillean Guilder", "Netherlands Antillean guilder", "Netherlands Antillean guilders", "ANG", "", ""},
	"AOA": {"Angolan Kwanza", "Angolan kwanza", "Angolan kwanzas", "AOA", "Kz", ""},
	"AOK": {"Angolan Kwanza (1977–1991)", "Angolan kwanza (1977–1991)", "Angolan kwanzas (1977–1991)", "AOK", "", ""},
	"AON": {"Angolan New Kwanza (1990–2000)", "Angolan new kwanza (1990–2000)", "Angolan new kwanzas (1990–2000)", "AON", "", ""},
	"AOR": {"Angolan Readjusted Kwanza (1995–1999)", "Angolan readjusted kwanza (1995–1999)", "Angolan readjusted kwanzas (1995–1999)", "AOR", "", ""},
	"ARA": {"Argentine Austral", "Argentine austral", "Argentine australs", "ARA", "", ""},
	"ARL": {"Argentine Peso Ley (1970–1983)", "Argentine peso ley (1970–1983)", "Argentine pesos ley (1970–1983)", "ARL", "", ""},
	"ARM": {"Argentine Peso (1881–1970)", "Argentine peso (1881–1970)", "Argentine pesos (1881–1970)", "ARM", "", ""},
	"ARP": {"Argentine Peso (1983–1985)", "Argentine peso (1983–1985)", "Argentine pesos (1983–1985)", "ARP", "", ""},
	"ARS": {"Argentine Peso", "Argentine peso", "Argentine pesos", "ARS", "$", ""},
	"ATS": {"Austrian Schilling", "Austrian schilling", "Austrian schillings", "ATS", "", ""},
	"AUD": {"Australian Dollar", "Australian dollar", "Australian dollars", "A$", "$", ""},
	"AWG": {"Aruban Florin", "Aruban florin", "Aruban florin", "AWG", "", ""},
	"AZM": {"Azerbaijani Manat (1993–2006)", "Azerbaijani manat (1993–2006)", "Azerbaijani manats (1993–2006)", "AZM", "", ""},
	"AZN": {"Azerbaijani Manat", "Azerbaijani manat", "Azerbaijani manats", "AZN", "", ""},
	"BAD": {"Bosnia-Herzegovina Dinar (1992–1994)", "Bosnia-Herzegovina dinar (1992–1994)", "Bosnia-Herzegovina dinars (1992–1994)", "BAD", "", ""},
	"BAM": {"Bosnia-Herzegovina Convertible Mark", "Bosnia-Herzegovina convertible mark", "Bosnia-Herzegovina convertible marks", "BAM", "KM", ""},
	"BAN": {"Bosnia-Herzegovina New Dinar (1994–1997)", "Bosnia-Herzegovina new dinar (1994–1997)", "Bosnia-Herzegovina new dinars (1994–1997)", "BAN", "", ""},
	"BBD": {"Barbadian Dollar", "Barbadian dollar", "Barbadian dollars", "BBD", "$", ""},
	"BDT": {"Bangladeshi Taka", "Bangladeshi taka", "Bangladeshi takas", "BDT", "৳", ""},
	"BEC": {"Belgian Franc (convertible)", "Belgian franc (convertible)", "Belgian francs (convertible)", "BEC", "", ""},
	"BEF": {"Belgian Franc", "Belgian franc", "Belgian francs", "BEF", "", ""},
	"BEL": {"Belgian Franc (financial)", "Belgian franc (financial)", "Belgian francs (financial)", "BEL", "", ""},
	"BGL": {"Bulgarian Hard Lev", "Bulgarian hard lev", "Bulgarian hard leva", "BGL", "", ""},
	"BGM": {"Bulgarian Socialist Lev", "Bulgarian socialist lev", "Bulgarian socialist leva", "BGM", "", ""},
	"BGN": {"Bulgarian Lev", "Bulgarian lev", "Bulgarian leva", "BGN", "", ""},
	"BGO": {"Bulgarian Lev (1879–1952)", "Bulgarian lev (1879–1952)", "Bulgarian leva (1879–1952)", "BGO", "", ""},
	"BHD": {"Bahraini Dinar", "Bahraini dinar", "Bahraini dinars", "BHD", "", ""},
	"BIF": {"Burundian Franc", "Burundian franc", "Burundian francs", "BIF", "", ""},
	"BMD": {"Bermudan Dollar", "Bermudan dollar", "Bermudan dollars", "BMD", "$", ""},
	"BND": {"Brunei Dollar", "Brunei dollar", "Brunei dollars", "BND", "$", ""},
	"BOB": {"Bolivian Boliviano", "Bolivian boliviano", "Bolivian bolivianos", "BOB", "Bs", ""},
	"BOL": {"Bolivian Boliviano (1863–1963)", "Bolivian boliviano (1863–1963)", "Bolivian bolivianos (1863–1963)", "BOL", "", ""},
	"BOP": {"Bolivian Peso", "Bolivian peso", "Bolivian pesos", "BOP", "", ""},
	"BOV": {"Bolivian Mvdol", "Bolivian mvdol", "Bolivian mvdols", "BOV", "", ""},
	"BRB": {"Brazilian New Cruzeiro (1967–1986)", "Brazilian new cruzeiro (1967–1986)", "Brazilian new cruzeiros (1967–1986)", "BRB", "", ""},
	"BRC": {"Brazilian Cruzado (1986–1989)", "Brazilian cruzado (1986–1989)", "Brazilian cruzados (1986–1989)", "BRC", "", ""},
	"BRE": {"Brazilian Cruzeiro (1990–1993)", "Brazilian cruzeiro (1990–1993)", "Brazilian cruzeiros (1990–1993)", "BRE", "", ""},
	"BRL": {"Brazilian Real", "Brazilian real", "Brazilian reals", "R$", "R$", ""},
	"BRN": {"Brazilian New Cruzado (1989–1990)", "Brazilian new cruzado (1989–1990)", "Brazilian new cruzados (1989–1990)", "BRN", "", ""},
	"BRR": {"Brazilian Cruzeiro (1993–1994)", "Brazilian cruzeiro (1993–1994)", "Brazilian cruzeiros (1993–1994)", "BRR", "", ""},
	"BRZ": {"Brazilian Cruzeiro (1942–1967)", "Brazilian cruzeiro (1942–1967)", "Brazilian cruzeiros (1942–1967)", "BRZ", "", ""},
	"BSD": {"Bahamian Dollar", "Bahamian dollar", "Bahamian dollars", "BSD", "$", ""},
	"BTN": {"Bhutanese Ngultrum", "Bhutanese ngultrum", "Bhutanese ngultrums", "BTN", "", ""},
	"BUK": {"Burmese Kyat", "Burmese kyat", "Burmese kyats", "BUK", "", ""},
	"BWP": {"Botswanan Pula", "Botswanan pula", "Botswanan pulas", "BWP", "P", ""},
	"BYB": {"Belarusian Ruble (1994–1999)", "Belarusian ruble (1994–1999)", "Belarusian rubles (1994–1999)", "BYB", "", ""},
	"BYN": {"Belarusian Ruble", "Belarusian ruble", "Belarusian rubles", "BYN", "р.", ""},
	"BYR": {"Belarusian Ruble (2000–2016)", "Belarusian ruble (2000–2016)", "Belarusian rubles (2000–2016)", "BYR", "", ""},
	"BZD": {"Belize Dollar", "Belize dollar", "Belize dollars", "BZD", "$", ""},
	"CAD": {"Canadian Dollar", "Canadian dollar", "Canadian dollars", "CA$", "$", ""},
	"CDF": {"Congolese Franc", "Congolese franc", "Congolese francs", "CDF", "", ""},
	"CHE": {"WIR Euro", "WIR euro", "WIR euros", "CHE", "", ""},
	"CHF": {"Swiss Franc", "Swiss franc", "Swiss francs", "CHF", "", ""},
	"CHW": {"WIR Franc", "WIR franc", "WIR francs", "CHW", "", ""},
	"CLE": {"Chilean Escudo", "Chilean escudo", "Chilean escudos", "CLE", "", ""},
	"CLF": {"Chilean Unit of Account (UF)", "Chilean unit of account (UF)", "Chilean units of account (UF)", "CLF", "", ""},
	"CLP": {"Chilean Peso", "Chilean peso", "Chilean pesos", "CLP", "$", ""},
	"CNH": {"Chinese Yuan (offshore)", "Chinese yuan (offshore)", "Chinese yuan (offshore)", "CNH", "", ""},
	"CNX": {"Chinese People’s Bank Dollar", "Chinese People’s Bank dollar", "Chinese People’s Bank dollars", "CNX", "", ""},
	"CNY": {"Chinese Yuan", "Chinese yuan", "Chinese yuan", "CN¥", "¥", ""},
	"COP": {"Colombian Peso", "Colombian peso", "Colombian pesos", "COP", "$", ""},
	"COU": {"Colombian Real Value Unit", "Colombian real value unit", "Colombian real value units", "COU", "", ""},
	"CRC": {"Costa Rican Colón", "Costa Rican colón", "Costa Rican colóns", "CRC", "₡", ""},
	"CSD": {"Serbian Dinar (2002–2006)", "Serbian dinar (2002–2006)", "Serbian dinars (2002–2006)", "CSD", "", ""},
	"CSK": {"Czechoslovak Hard Koruna", "Czechoslovak hard koruna", "Czechoslovak hard korunas", "CSK", "", ""},
	"CUC": {"Cuban Convertible Peso", "Cuban convertible peso", "Cuban convertible pesos", "CUC", "$", ""},
	"CUP": {"Cuban Peso", "Cuban peso", "Cuban pesos", "CUP", "$", ""},
	"CVE": {"Cape Verdean Escudo", "Cape Verdean escudo", "Cape Verdean escudos", "CVE", "", ""},
	"CYP": {"Cypriot Pound", "Cypriot pound", "Cypriot pounds", "CYP", "", ""},
	"CZK": {"Czech Koruna", "Czech koruna", "Czech korunas", "CZK", "Kč", ""},
	"DDM": {"East German Mark", "East German mark", "East German marks", "DDM", "", ""},
	"DEM": {"German Mark", "German mark", "German marks", "DEM", "", ""},
	"DJF": {"Djiboutian Franc", "Djiboutian franc", "Djiboutian francs", "DJF", "", ""},
	"DKK": {"Danish Krone", "Danish krone", "Danish kroner", "DKK", "kr", ""},
	"DOP": {"Dominican Peso", "Dominican peso", "Dominican pesos", "DOP", "$", ""},
	"DZD": {"Algerian Dinar", "Algerian dinar", "Algerian dinars", "DZD", "", ""},
	"ECS": {"Ecuadorian Sucre", "Ecuadorian sucre", "Ecuadorian sucres", "ECS", "", ""},
	"ECV": {"Ecuadorian Unit of Constant Value", "Ecuadorian unit of constant value", "Ecuadorian units of constant value", "ECV", "", ""},
	"EEK": {"Estonian Kroon", "Estonian kroon", "Estonian kroons", "EEK", "", ""},
	"EGP": {"Egyptian Pound", "Egyptian pound", "Egyptian pounds", "EGP", "E£", ""},
	"ERN": {"Eritrean Nakfa", "Eritrean nakfa", "Eritrean nakfas", "ERN", "", ""},
	"ESA": {"Spanish Peseta (A account)", "Spanish peseta (A account)", "Spanish pesetas (A account)", "ESA", "", ""},
	"ESB": {"Spanish Peseta (convertible account)", "Spanish peseta (convertible account)", "Spanish pesetas (convertible account)", "ESB", "", ""},
	"ESP": {"Spanish Peseta", "Spanish peseta", "Spanish pesetas", "ESP", "₧", ""},
	"ETB": {"Ethiopian Birr", "Ethiopian birr", "Ethiopian birrs", "ETB", "", ""},
	"EUR": {"Euro", "euro", "euros", "€", "€", ""},
	"FIM": {"Finnish Markka", "Finnish markka", "Finnish markkas", "FIM", "", ""},
	"FJD": {"Fijian Dollar", "Fijian dollar", "Fijian dollars", "FJD", "$", ""},
	"FKP": {"Falkland Islands Pound", "Falkland Islands pound", "Falkland Islands pounds", "FKP", "£", ""},
	"FRF": {"French Franc", "French franc", "French francs", "FRF", "", ""},
	"GBP": {"British Pound", "British pound", "British pounds", "£", "£", ""},
	"GEK": {"Georgian Kupon Larit", "Georgian kupon larit", "Georgian kupon larits", "GEK", "", ""},
	"GEL": {"Georgian Lari", "Georgian lari", "Georgian laris", "GEL", "₾", ""},
	"GHC": {"Ghanaian Cedi (1979–2007)", "Ghanaian cedi (1979–2007)", "Ghanaian cedis (1979–2007)", "GHC", "", ""},
	"GHS": {"Ghanaian Cedi", "Ghanaian cedi", "Ghanaian cedis", "GHS", "", ""},
	"GIP": {"Gibraltar Pound", "Gibraltar pound", "Gibraltar pounds", "GIP", "£", ""},
	"GMD": {"Gambian Dalasi", "Gambian dalasi", "Gambian dalasis", "GMD", "", ""},
	"GNF": {"Guinean Franc", "Guinean franc", "Guinean francs", "GNF", "FG", ""},
	"GNS": {"Guinean Syli", "Guinean syli", "Guinean sylis", "GNS", "", ""},
	"GQE": {"Equatorial Guinean Ekwele", "Equatorial Guinean ekwele", "Equatorial Guinean ekwele", "GQE", "", ""},
	"GRD": {"Greek Drachma", "Greek drachma", "Greek drachmas", "GRD", "", ""},
	"GTQ": {"Guatemalan Quetzal", "Guatemalan quetzal", "Guatemalan quetzals", "GTQ", "Q", ""},
	"GWE": {"Portuguese Guinea Escudo", "Portuguese Guinea escudo", "Portuguese Guinea escudos", "GWE", "", ""},
	"GWP": {"Guinea-Bissau Peso", "Guinea-Bissau peso", "Guinea-Bissau pesos", "GWP", "", ""},
	"GYD": {"Guyanaese Dollar", "Guyanaese dollar", "Guyanaese dollars", "GYD", "$", ""},
	"HKD": {"Hong Kong Dollar", "Hong Kong dollar", "Hong Kong dollars", "HK$", "$", ""},
	"HNL": {"Honduran Lempira", "Honduran lempira", "Honduran lempiras", "HNL", "L", ""},
	"HRD": {"Croatian Dinar", "Croatian dinar", "Croatian dinars", "HRD", "", ""},
	"HRK": {"Croatian Kuna", "Croatian kuna", "Croatian kunas", "HRK", "kn", ""},
	"HTG": {"Haitian Gourde", "Haitian gourde", "Haitian gourdes", "HTG", "", ""},
	"HUF": {"Hungarian Forint", "Hungarian forint", "Hungarian forints", "HUF", "Ft", ""},
	"IDR": {"Indonesian Rupiah", "Indonesian rupiah", "Indonesian rupiahs", "IDR", "Rp", ""},
	"IEP": {"Irish Pound", "Irish pound", "Irish pounds", "IEP", "", ""},
	"ILP": {"Israeli Pound", "Israeli pound", "Israeli pounds", "ILP", "", ""},
	"ILR": {"Israeli Shekel (1980–1985)", "Israeli shekel (1980–1985)", "Israeli shekels (1980–1985)", "ILR", "", ""},
	"ILS": {"Israeli New Shekel", "Israeli new shekel", "Israeli new shekels", "₪", "₪", ""},
	"INR": {"Indian Rupee", "Indian rupee", "Indian rupees", "₹", "₹", ""},
	"IQD": {"Iraqi Dinar", "Iraqi dinar", "Iraqi dinars", "IQD", "", ""},
	"IRR": {"Iranian Rial", "Iranian rial", "Iranian rials", "IRR", "", ""},
	"ISJ": {"Icelandic Króna (1918–1981)", "Icelandic króna (1918–1981)", "Icelandic krónur (1918–1981)", "ISJ", "", ""},
	"ISK": {"Icelandic Króna", "Icelandic króna", "Icelandic krónur", "ISK", "kr", ""},
	"ITL": {"Italian Lira", "Italian lira", "Italian liras", "ITL", "", ""},
	"JMD": {"Jamaican Dollar", "Jamaican dollar", "Jamaican dollars", "JMD", "$", ""},
	"JOD": {"Jordanian Dinar", "Jordanian dinar", "Jordanian dinars", "JOD", "", ""},
	"JPY": {"Japanese Yen", "Japanese yen", "Japanese yen", "¥", "¥", ""},
	"KES": {"Kenyan Shilling", "Kenyan shilling", "Kenyan shillings", "KES", "", ""},
	"KGS": {"Kyrgystani Som", "Kyrgystani som", "Kyrgystani soms", "KGS", "", ""},
	"KHR": {"Cambodian Riel", "Cambodian riel", "Cambodian riels", "KHR", "៛", ""},
	"KMF": {"Comorian Franc", "Comorian franc", "Comorian francs", "KMF", "CF", ""},
	"KPW": {"North Korean Won", "North Korean won", "North Korean won", "KPW", "₩", ""},
	"KRH": {"South Korean Hwan (1953–1962)", "South Korean hwan (1953–1962)", "South Korean hwan (1953–1962)", "KRH", "", ""},
	"KRO": {"South Korean Won (1945–1953)", "South Korean won (1945–1953)", "South Korean won (1945–1953)", "KRO", "", ""},
	"KRW": {"South Korean Won", "South Korean won", "South Korean won", "₩", "₩", ""},
	"KWD": {"Kuwaiti Dinar", "Kuwaiti dinar", "Kuwaiti dinars", "KWD", "", ""},
	"KYD": {"Cayman Islands Dollar", "Cayman Islands dollar", "Cayman Islands dollars", "KYD", "$", ""},
	"KZT": {"Kazakhstani Tenge", "Kazakhstani tenge", "Kazakhstani tenges", "KZT", "₸", ""},
	"LAK": {"Laotian Kip", "Laotian kip", "Laotian kips", "LAK", "₭", ""},
	"LBP": {"Lebanese Pound", "Lebanese pound", "Lebanese pounds", "LBP", "L£", ""},
	"LKR": {"Sri Lankan Rupee", "Sri Lankan rupee", "Sri Lankan rupees", "LKR", "Rs", ""},
	"LRD": {"Liberian Dollar", "Liberian dollar", "Liberian dollars", "LRD", "$", ""},
	"LSL": {"Lesotho Loti", "Lesotho loti", "Lesotho lotis", "LSL", "", ""},
	"LTL": {"Lithuanian Litas", "Lithuanian litas", "Lithuanian litai", "LTL", "Lt", ""},
	"LTT": {"Lithuanian Talonas", "Lithuanian talonas", "Lithuanian talonases", "LTT", "", ""},
	"LUC": {"Luxembourgian Convertible Franc", "Luxembourgian convertible franc", "Luxembourgian convertible francs", "LUC", "", ""},
	"LUF": {"Luxembourgian Franc", "Luxembourgian franc", "Luxembourgian francs", "LUF", "", ""},
	"LUL": {"Luxembourg Financial Franc", "Luxembourg financial franc", "Luxembourg financial francs", "LUL", "", ""},
	"LVL": {"Latvian Lats", "Latvian lats", "Latvian lati", "LVL", "Ls", ""},
	"LVR": {"Latvian Ruble", "Latvian ruble", "Latvian rubles", "LVR", "", ""},
	"LYD": {"Libyan Dinar", "Libyan dinar", "Libyan dinars", "LYD", "", ""},
	"MAD": {"Moroccan Dirham", "Moroccan dirham", "Moroccan dirhams", "MAD", "", ""},
	"MAF": {"Moroccan Franc", "Moroccan franc", "Moroccan francs", "MAF", "", ""},
	"MCF": {"Monegasque Franc", "Monegasque franc", "Monegasque francs", "MCF", "", ""},
	"MDC": {"Moldovan Cupon", "Moldovan cupon", "Moldovan cupon", "MDC", "", ""},
	"MDL": {"Moldovan Leu", "Moldovan leu", "Moldovan lei", "MDL", "", ""},
	"MGA": {"Malagasy Ariary", "Malagasy ariary", "Malagasy ariaries", "MGA", "Ar", ""},
	"MGF": {"Malagasy Franc", "Malagasy franc", "Malagasy francs", "MGF", "", ""},
	"MKD": {"Macedonian Denar", "Macedonian denar", "Macedonian denari", "MKD", "", ""},
	"MKN": {"Macedonian Denar (1992–1993)", "Macedonian denar (1992–1993)", "Macedonian denari (1992–1993)", "MKN", "", ""},
	"MLF": {"Malian Franc", "Malian franc", "Malian francs", "MLF", "", ""},
	"MMK": {"Myanmar Kyat", "Myanmar kyat", "Myanmar kyats", "MMK", "K", ""},
	"MNT": {"Mongolian Tugrik", "Mongolian tugrik", "Mongolian tugriks", "MNT", "₮", ""},
	"MOP": {"Macanese Pataca", "Macanese pataca", "Macanese patacas", "MOP", "", ""},
	"MRO": {"Mauritanian Ouguiya (1973–2017)", "Mauritanian ouguiya (1973–2017)", "Mauritanian ouguiyas (1973–2017)", "MRO", "", ""},
	"MRU": {"Mauritanian Ouguiya", "Mauritanian ouguiya", "Mauritanian ouguiyas", "MRU", "", ""},
	"MTL": {"Maltese Lira", "Maltese lira", "Maltese lira", "MTL", "", ""},
	"MTP": {"Maltese Pound", "Maltese pound", "Maltese pounds", "MTP", "", ""},
	"MUR": {"Mauritian Rupee", "Mauritian rupee", "Mauritian rupees", "MUR", "Rs", ""},
	"MVP": {"Maldivian Rupee (1947–1981)", "Maldivian rupee (1947–1981)", "Maldivian rupees (1947–1981)", "MVP", "", ""},
	"MVR": {"Maldivian Rufiyaa", "Maldivian rufiyaa", "Maldivian rufiyaas", "MVR", "", ""},
	"MWK": {"Malawian Kwacha", "Malawian kwacha", "Malawian kwachas", "MWK", "", ""},
	"MXN": {"Mexican Peso", "Mexican peso", "Mexican pesos", "MX$", "$", ""},
	"MXP": {"Mexican Silver Peso (1861–1992)", "Mexican silver peso (1861–1992)", "Mexican silver pesos (1861–1992)", "MXP", "", ""},
	"MXV": {"Mexican Investment Unit", "Mexican investment unit", "Mexican investment units", "MXV", "", ""},
	"MYR": {"Malaysian Ringgit", "Malaysian ringgit", "Malaysian ringgits", "MYR", "RM", ""},
	"MZE": {"Mozambican Escudo", "Mozambican escudo", "Mozambican escudos", "MZE", "", ""},
	"MZM": {"Mozambican Metical (1980–2006)", "Mozambican metical (1980–2006)", "Mozambican meticals (1980–2006)", "MZM", "", ""},
	"MZN": {"Mozambican Metical", "Mozambican metical", "Mozambican meticals", "MZN", "", ""},
	"NAD": {"Namibian Dollar", "Namibian dollar", "Namibian dollars", "NAD", "$", ""},
	"NGN": {"Nigerian Naira", "Nigerian naira", "Nigerian nairas", "NGN", "₦", ""},
	"NIC": {"Nicaraguan Córdoba (1988–1991)", "Nicaraguan córdoba (1988–1991)", "Nicaraguan córdobas (1988–1991)", "NIC", "", ""},
	"NIO": {"Nicaraguan Córdoba", "Nicaraguan córdoba", "Nicaraguan córdobas", "NIO", "C$", ""},
	"NLG": {"Dutch Guilder", "Dutch guilder", "Dutch guilders", "NLG", "", ""},
	"NOK": {"Norwegian Krone", "Norwegian krone", "Norwegian kroner", "NOK", "kr", ""},
	"NPR": {"Nepalese Rupee", "Nepalese rupee", "Nepalese rupees", "NPR", "Rs", ""},
	"NZD": {"New Zealand Dollar", "New Zealand dollar", "New Zealand dollars", "NZ$", "$", ""},
	"OMR": {"Omani Rial", "Omani rial", "Omani rials", "OMR", "", ""},
	"PAB": {"Panamanian Balboa", "Panamanian balboa", "Panamanian balboas", "PAB", "", ""},
	"PEI": {"Peruvian Inti", "Peruvian inti", "Peruvian intis", "PEI", "", ""},
	"PEN": {"Peruvian Sol", "Peruvian sol", "Peruvian soles", "PEN", "", ""},
	"PES": {"Peruvian Sol (1863–1965)", "Peruvian sol (1863–1965)", "Peruvian soles (1863–1965)", "PES", "", ""},
	"PGK": {"Papua New Guinean Kina", "Papua New Guinean kina", "Papua New Guinean kina", "PGK", "", ""},
	"PHP": {"Philippine Piso", "Philippine piso", "Philippine pisos", "PHP", "₱", ""},
	"PKR": {"Pakistani Rupee", "Pakistani rupee", "Pakistani rupees", "PKR", "Rs", ""},
	"PLN": {"Polish Zloty", "Polish zloty", "Polish zlotys", "PLN", "zł", ""},
	"PLZ": {"Polish Zloty (1950–1995)", "Polish zloty (PLZ)", "Polish zlotys (PLZ)", "PLZ", "", ""},
	"PTE": {"Portuguese Escudo", "Portuguese escudo", "Portuguese escudos", "PTE", "", ""},
	"PYG": {"Paraguayan Guarani", "Paraguayan guarani", "Paraguayan guaranis", "PYG", "₲", ""},
	"QAR": {"Qatari Rial", "Qatari rial", "Qatari rials", "QAR", "", ""},
	"RHD": {"Rhodesian Dollar", "Rhodesian dollar", "Rhodesian dollars", "RHD", "", ""},
	"ROL": {"Romanian Leu (1952–2006)", "Romanian leu (1952–2006)", "Romanian Lei (1952–2006)", "ROL", "", ""},
	"RON": {"Romanian Leu", "Romanian leu", "Romanian lei", "RON", "lei", ""},
	"RSD": {"Serbian Dinar", "Serbian dinar", "Serbian dinars", "RSD", "", ""},
	"RUB": {"Russian Ruble", "Russian ruble", "Russian rubles", "RUB", "₽", ""},
	"RUR": {"Russian Ruble (1991–1998)", "Russian ruble (1991–1998)", "Russian rubles (1991–1998)", "RUR", "р.", ""},
	"RWF": {"Rwandan Franc", "Rwandan franc", "Rwandan francs", "RWF", "RF", ""},
	"SAR": {"Saudi Riyal", "Saudi riyal", "Saudi riyals", "SAR", "", ""},
	"SBD": {"Solomon Islands Dollar", "Solomon Islands dollar", "Solomon Islands dollars", "SBD", "$", ""},
	"SCR": {"Seychellois Rupee", "Seychellois rupee", "Seychellois rupees", "SCR", "", ""},
	"SDD": {"Sudanese Dinar (1992–2007)", "Sudanese dinar (1992–2007)", "Sudanese dinars (1992–2007)", "SDD", "", ""},
	"SDG": {"Sudanese Pound", "Sudanese pound", "Sudanese pounds", "SDG", "", ""},
	"SDP": {"Sudanese Pound (1957–1998)", "Sudanese pound (1957–1998)", "Sudanese pounds (1957–1998)", "SDP", "", ""},
	"SEK": {"Swedish Krona", "Swedish krona", "Swedish kronor", "SEK", "kr", ""},
	"SGD": {"Singapore Dollar", "Singapore dollar", "Singapore dollars", "SGD", "$", ""},
	"SHP": {"St. Helena Pound", "St. Helena pound", "St. Helena pounds", "SHP", "£", ""},
	"SIT": {"Slovenian Tolar", "Slovenian tolar", "Slovenian tolars", "SIT", "", ""},
	"SKK": {"Slovak Koruna", "Slovak koruna", "Slovak korunas", "SKK", "", ""},
	"SLL": {"Sierra Leonean Leone", "Sierra Leonean leone", "Sierra Leonean leones", "SLL", "", ""},
	"SOS": {"Somali Shilling", "Somali shilling", "Somali shillings", "SOS", "", ""},
	"SRD": {"Surinamese Dollar", "Surinamese dollar", "Surinamese dollars", "SRD", "$", ""},
	"SRG": {"Surinamese Guilder", "Surinamese guilder", "Surinamese guilders", "SRG", "", ""},
	"SSP": {"South Sudanese Pound", "South Sudanese pound", "South Sudanese pounds", "SSP", "£", ""},
	"STD": {"São Tomé & Príncipe Dobra (1977–2017)", "São Tomé & Príncipe dobra (1977–2017)", "São Tomé & Príncipe dobras (1977–2017)", "STD", "", ""},
	"STN": {"São Tomé & Príncipe Dobra", "São Tomé & Príncipe dobra", "São Tomé & Príncipe dobras", "STN", "Db", ""},
	"SUR": {"Soviet Rouble", "Soviet rouble", "Soviet roubles", "SUR", "", ""},
	"SVC": {"Salvadoran Colón", "Salvadoran colón", "Salvadoran colones", "SVC", "", ""},
	"SYP": {"Syrian Pound", "Syrian pound", "Syrian pounds", "SYP", "£", ""},
	"SZL": {"Swazi Lilangeni", "Swazi lilangeni", "Swazi emalangeni", "SZL", "", ""},
	"THB": {"Thai Baht", "Thai baht", "Thai baht", "THB", "฿", ""},
	"TJR": {"Tajikistani Ruble", "Tajikistani ruble", "Tajikistani rubles", "TJR", "", ""},
	"TJS": {"Tajikistani Somoni", "Tajikistani somoni", "Tajikistani somonis", "TJS", "", ""},
	"TMM": {"Turkmenistani Manat (1993–2009)", "Turkmenistani manat (1993–2009)", "Turkmenistani manat (1993–2009)", "TMM", "", ""},
	"TMT": {"Turkmenistani Manat", "Turkmenistani manat", "Turkmenistani manat", "TMT", "", ""},
	"TND": {"Tunisian Dinar", "Tunisian dinar", "Tunisian dinars", "TND", "", ""},
	"TOP": {"Tongan Paʻanga", "Tongan paʻanga", "Tongan paʻanga", "TOP", "T$", ""},
	"TPE": {"Timorese Escudo", "Timorese escudo", "Timorese escudos", "TPE", "", ""},
	"TRL": {"Turkish Lira (1922–2005)", "Turkish lira (1922–2005)", "Turkish Lira (1922–2005)", "TRL", "", ""},
	"TRY": {"Turkish Lira", "Turkish lira", "Turkish Lira", "TRY", "₺", "TL"},
	"TTD": {"Trinidad & Tobago Dollar", "Trinidad & Tobago dollar", "Trinidad & Tobago dollars", "TTD", "$", ""},
	"TWD": {"New Taiwan Dollar", "New Taiwan dollar", "New Taiwan dollars", "NT$", "$", ""},
	"TZS": {"Tanzanian Shilling", "Tanzanian shilling", "Tanzanian shillings", "TZS", "", ""},
	"UAH": {"Ukrainian Hryvnia", "Ukrainian hryvnia", "Ukrainian hryvnias", "UAH", "₴", ""},
	"UAK": {"Ukrainian Karbovanets", "Ukrainian karbovanets", "Ukrainian karbovantsiv", "UAK", "", ""},
	"UGS": {"Ugandan Shilling (1966–1987)", "Ugandan shilling (1966–1987)", "Ugandan shillings (1966–1987)", "UGS", "", ""},
	"UGX": {"Ugandan Shilling", "Ugandan shilling", "Ugandan shillings", "UGX", "", ""},
	"USD": {"US Dollar", "US dollar", "US dollars", "$", "$", ""},
	"USN": {"US Dollar (Next day)", "US dollar (next day)", "US dollars (next day)", "USN", "", ""},
	"USS": {"US Dollar (Same day)", "US dollar (same day)", "US dollars (same day)", "USS", "", ""},
	"UYI": {"Uruguayan Peso (Indexed Units)", "Uruguayan peso (indexed units)", "Uruguayan pesos (indexed units)", "UYI", "", ""},
	"UYP": {"Uruguayan Peso (1975–1993)", "Uruguayan peso (1975–1993)", "Uruguayan pesos (1975–1993)", "UYP", "", ""},
	"UYU": {"Uruguayan Peso", "Uruguayan peso", "Uruguayan pesos", "UYU", "$", ""},
	"UYW": {"Uruguayan Nominal Wage Index Unit", "Uruguayan nominal wage index unit", "Uruguayan nominal wage index units", "UYW", "", ""},
	"UZS": {"Uzbekistani Som", "Uzbekistani som", "Uzbekistani som", "UZS", "", ""},
	"VEB": {"Venezuelan Bolívar (1871–2008)", "Venezuelan bolívar (1871–2008)", "Venezuelan bolívars (1871–2008)", "VEB", "", ""},
	"VEF": {"Venezuelan Bolívar (2008–2018)", "Venezuelan bolívar (2008–2018)", "Venezuelan bolívars (2008–2018)", "VEF", "Bs", ""},
	"VES": {"Venezuelan Bolívar", "Venezuelan bolívar", "Venezuelan bolívars", "VES", "", ""},
	"VND": {"Vietnamese Dong", "Vietnamese dong", "Vietnamese dong", "₫", "₫", ""},
	"VNN": {"Vietnamese Dong (1978–1985)", "Vietnamese dong (1978–1985)", "Vietnamese dong (1978–1985)", "VNN", "", ""},
	"VUV": {"Vanuatu Vatu", "Vanuatu vatu", "Vanuatu vatus", "VUV", "", ""},
	"WST": {"Samoan Tala", "Samoan tala", "Samoan tala", "WST", "", ""},
	"XAF": {"Central African CFA Franc", "Central African CFA franc", "Central African CFA francs", "FCFA", "", ""},
	"XAG": {"Silver", "troy ounce of silver", "troy ounces of silver", "XAG", "", ""},
	"XAU": {"Gold", "troy ounce of gold", "troy ounces of gold", "XAU", "", ""},
	"XBA": {"European Composite Unit", "European composite unit", "European composite units", "XBA", "", ""},
	"XBB": {"European Monetary Unit", "European monetary unit", "European monetary units", "XBB", "", ""},
	"XBC": {"European Unit of Account (XBC)", "European unit of account (XBC)", "European units of account (XBC)", "XBC", "", ""},
	"XBD": {"European Unit of Account (XBD)", "European unit of account (XBD)", "European units of account (XBD)", "XBD", "", ""},
	"XCD": {"East Caribbean Dollar", "East Caribbean dollar", "East Caribbean dollars", "EC$", "$", ""},
	"XDR": {"Special Drawing Rights", "special drawing rights", "special drawing rights", "XDR", "", ""},
	"XEU": {"European Currency Unit", "European currency unit", "European currency units", "XEU", "", ""},
	"XFO": {"French Gold Franc", "French gold franc", "French gold francs", "XFO", "", ""},
	"XFU": {"French UIC-Franc", "French UIC-franc", "French UIC-francs", "XFU", "", ""},
	"XOF": {"West African CFA Franc", "West African CFA franc", "West African CFA francs", "CFA", "", ""},
	"XPD": {"Palladium", "troy ounce of palladium", "troy ounces of palladium", "XPD", "", ""},
	"XPF": {"CFP Franc", "CFP franc", "CFP francs", "CFPF", "", ""},
	"XPT": {"Platinum", "troy ounce of platinum", "troy ounces of platinum", "XPT", "", ""},
	"XRE": {"RINET Funds", "RINET Funds unit", "RINET Funds units", "XRE", "", ""},
	"XSU": {"Sucre", "Sucre", "Sucres", "XSU", "", ""},
	"XTS": {"Testing Currency Code", "Testing Currency unit", "Testing Currency units", "XTS", "", ""},
	"XUA": {"ADB Unit of Account", "ADB unit of account", "ADB units of account", "XUA", "", ""},
	"XXX": {"Unknown Currency", "(unknown unit of currency)", "(unknown currency)", "¤", "", ""},
	"YDD": {"Yemeni Dinar", "Yemeni dinar", "Yemeni dinars", "YDD", "", ""},
	"YER": {"Yemeni Rial", "Yemeni rial", "Yemeni rials", "YER", "", ""},
	"YUD": {"Yugoslavian Hard Dinar (1966–1990)", "Yugoslavian hard dinar (1966–1990)", "Yugoslavian hard dinars (1966–1990)", "YUD", "", ""},
	"YUM": {"Yugoslavian New Dinar (1994–2002)", "Yugoslavian new dinar (1994–2002)", "Yugoslavian new dinars (1994–2002)", "YUM", "", ""},
	"YUN": {"Yugoslavian Convertible Dinar (1990–1992)", "Yugoslavian convertible dinar (1990–1992)", "Yugoslavian convertible dinars (1990–1992)", "YUN", "", ""},
	"YUR": {"Yugoslavian Reformed Dinar (1992–1993)", "Yugoslavian reformed dinar (1992–1993)", "Yugoslavian reformed dinars (1992–1993)", "YUR", "", ""},
	"ZAL": {"South African Rand (financial)", "South African rand (financial)", "South African rands (financial)", "ZAL", "", ""},
	"ZAR": {"South African Rand", "South African rand", "South African rand", "ZAR", "R", ""},
	"ZMK": {"Zambian Kwacha (1968–2012)", "Zambian kwacha (1968–2012)", "Zambian kwachas (1968–2012)", "ZMK", "", ""},
	"ZMW": {"Zambian Kwacha", "Zambian kwacha", "Zambian kwachas", "ZMW", "ZK", ""},
	"ZRN": {"Zairean New Zaire (1993–1998)", "Zairean new zaire (1993–1998)", "Zairean new zaires (1993–1998)", "ZRN", "", ""},
	"ZRZ": {"Zairean Zaire (1971–1993)", "Zairean zaire (1971–1993)", "Zairean zaires (1971–1993)", "ZRZ", "", ""},
	"ZWD": {"Zimbabwean Dollar (1980–2008)", "Zimbabwean dollar (1980–2008)", "Zimbabwean dollars (1980–2008)", "ZWD", "", ""},
	"ZWL": {"Zimbabwean Dollar (2009)", "Zimbabwean dollar (2009)", "Zimbabwean dollars (2009)", "ZWL", "", ""},
	"ZWR": {"Zimbabwean Dollar (2008)", "Zimbabwean dollar (2008)", "Zimbabwean dollars (2008)", "ZWR", "", ""},
}
